cache:
  paths:
    - node_modules

Dev Build:
  tags:
    - shared
  only:
    - develop@ai-call-platform/yiwise-wepage
  image: node:10.10.0
  stage: build
  script:
    - npm i -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm install
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist


Prod Build:
  tags:
    - shared
  only:
    - master@ai-call-platform/yiwise-wepage
  image: node:10.10.0
  stage: build
  script:
    - npm i -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm install
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  tags:
    - shared
  only:
    - develop@ai-call-platform/yiwise-wepage
  image: yiwise/alpine:deploy
  stage: deploy
  script:
    - ls -la
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_TEST" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ $TEST_SERVER

production1:
  tags:
    - shared
  only:
    - master@ai-call-platform/yiwise-wepage
  image: yiwise/alpine:deploy
  stage: deploy
  script:
    - ls -la
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_PROD1" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ $PRODUCTION_SERVER1

production2:
  tags:
    - shared
  only:
    - master@ai-call-platform/yiwise-wepage
  image: yiwise/alpine:deploy
  stage: deploy
  script:
    - ls -la
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_PROD2" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ $PRODUCTION_SERVER2
